version: '3.8'

services:
  mcp-website:
    build: .
    container_name: mcp-agent-website
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge